
package adder;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdderWebService", targetNamespace = "http://adder/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdderWebService {


    /**
     * 
     * @param md
     * @param device
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "setMonitorData", targetNamespace = "http://adder/", className = "adder.SetMonitorData")
    @Action(input = "http://adder/AdderWebService/setMonitorData")
    public void setMonitorData(
        @WebParam(name = "device", targetNamespace = "")
        String device,
        @WebParam(name = "md", targetNamespace = "")
        MonitorData md);

}
